name: "CI:lintyaml"

on:
  pull_request:
    paths:
      - "**.yaml"
      - ".github/workflows/phpcs.yml"

jobs:
  run-phpcs:
    runs-on: ubuntu-latest
    container:
      image:  prooph/composer:7.2
    steps:
      - uses: actions/checkout@v2
      - name: Install vendors
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Lint yaml
        run: composer lint:yaml